//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegITProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.RegisterDatas = new HashSet<RegisterData>();
            this.TANs = new HashSet<TAN>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<RegisterData> RegisterDatas { get; set; }
        public virtual ICollection<TAN> TANs { get; set; }
    }
}
