//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegITProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterData
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime birth { get; set; }
        public string adress { get; set; }
        public string productInfo { get; set; }
        public System.DateTime buydate { get; set; }
        public System.DateTime registerdate { get; set; }
        public int ProductId { get; set; }
        public int TANId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TAN TAN { get; set; }
    }
}
